// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAV9JLQYabAIh_wtHAerRz7udMlMqz5h9s',
    appId: '1:772917006496:web:d57af59a6b33e58e75f9c5',
    messagingSenderId: '772917006496',
    projectId: 'raia-app-81e71',
    authDomain: 'raia-app-81e71.firebaseapp.com',
    storageBucket: 'raia-app-81e71.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIgLHfGlZB5u_vQxxwPupiGpZ5LJtIooc',
    appId: '1:772917006496:android:d4aca8938183b82775f9c5',
    messagingSenderId: '772917006496',
    projectId: 'raia-app-81e71',
    storageBucket: 'raia-app-81e71.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKvQPaUZVOkbc_00cvEBPYp5FJT8LAIzU',
    appId: '1:772917006496:ios:600274681260c8d275f9c5',
    messagingSenderId: '772917006496',
    projectId: 'raia-app-81e71',
    storageBucket: 'raia-app-81e71.firebasestorage.app',
    iosBundleId: 'com.example.riraApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKvQPaUZVOkbc_00cvEBPYp5FJT8LAIzU',
    appId: '1:772917006496:ios:600274681260c8d275f9c5',
    messagingSenderId: '772917006496',
    projectId: 'raia-app-81e71',
    storageBucket: 'raia-app-81e71.firebasestorage.app',
    iosBundleId: 'com.example.riraApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAV9JLQYabAIh_wtHAerRz7udMlMqz5h9s',
    appId: '1:772917006496:web:cbc3b341391c5f8375f9c5',
    messagingSenderId: '772917006496',
    projectId: 'raia-app-81e71',
    authDomain: 'raia-app-81e71.firebaseapp.com',
    storageBucket: 'raia-app-81e71.firebasestorage.app',
  );
}
